version: "3"

services:
  webapp:
    build: ./webapp
    volumes:
      - .:/webapp
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
